# .github/release.yml

changelog:
  categories:
    - title: 🏕 Features
      labels:
        - enhancement
    - title: 🚧 Fix
      labels:
        - bug fix
    - title: ⚛️ Chore
      labels:
        - chore
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
